worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;

    server {
        listen 80;
        server_name _;
        root /var/www/html;
        index index.html;

        location = /health.html {
            access_log off;
            add_header Cache-Control "no-store";
        }

        location / {
            add_header Cache-Control "no-cache";
            try_files $uri $uri/ =404;
        }
    }
}
