worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    server_tokens off;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_min_length 1k;

    server {
        listen 80;
        server_name _;
        root /var/www/html;
        index index.html;

        location = /health.html {
            access_log off;
            add_header Cache-Control "no-store";
        }

        location ~* \.(?:css|js|svg|png|jpe?g|webp|gif|woff2?)$ {
            if ($args ~* "(^|&)v=") {
                add_header Cache-Control "public, max-age=86400";
                expires 1d;
            }
            if ($args !~* "(^|&)v=") {
                add_header Cache-Control "no-store, must-revalidate";
                add_header Pragma "no-cache";
                expires -1;
            }
        }

        location / {
            add_header Cache-Control "no-cache";
            try_files $uri $uri/ /index.html;
        }
    }
}
